version: "3.9"
services:
  database:
    image: postgres:latest
    ports:
      - "5431:5432"
    tty: true
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db_data:/db
    networks:
      database-app:
  app:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - database
    networks:
      database-app:
    environment:
      GIN_MODE: release
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PORT: ${PORT}
    restart: on-failure
volumes:
  db_data:
networks:
  database-app:
